<?php
namespace LUNIVERS_THEME\Inc\Classes;

use LUNIVERS_THEME\Inc\Traits\Singleton;

class Assets {
    use Singleton;

    protected function __construct() {
        add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_front' ] );
        add_action( 'wp_head', [ $this, 'preload_fonts' ], 1 );
        add_action( 'wp_head', [ $this, 'preload_lcp_image' ], 2 );

        add_filter( 'script_loader_tag', [ $this, 'add_module_attribute' ], 10, 3 );
    }

    /**
     * Preload des fonts critiques (Geist)
     */
    public function preload_fonts() {
        ?>
        <!-- Preload Geist Variable Font -->
        <link
            rel="preconnect"
            href="https://fonts.googleapis.com"
            crossorigin
        >
        <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossorigin
        >
        <link
            rel="preload"
            href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&family=Geist:wght@100..900&family=Geist+Mono:wght@100..900&display=swap"
            as="style"
            onload="this.onload=null;this.rel='stylesheet'"
        >
        <noscript>
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&family=Geist:wght@100..900&family=Geist+Mono:wght@100..900&display=swap"
            >
        </noscript>
        <?php
    }

    /**
     * Preload de l'image LCP (hero) pour améliorer le Largest Contentful Paint
     */
    public function preload_lcp_image() {
        // Seulement sur la page d'accueil
        if ( ! is_front_page() || ! function_exists( 'get_field' ) ) {
            return;
        }

        $slider = get_field( 'slider' );

        // Si on a un slider, précharger la première image
        if ( $slider && is_array( $slider ) && ! empty( $slider ) ) {
            $first_slide = $slider[0];
            $image_url   = $first_slide['url'] ?? '';

            if ( $image_url ) {
                ?>
                <link rel="preload" as="image" href="<?php echo esc_url( $image_url ); ?>" fetchpriority="high">
                <?php
            }
        }
    }

    public function enqueue_front() {
        // Localize script for AJAX
        wp_localize_script(
            'jquery',
            'ajaxurl',
            admin_url( 'admin-ajax.php' )
        );

        // Vite dev server in local/dev
        if ( in_array( LUNIVERS_THEME_ENV, [ 'local', 'development' ], true ) ) {
            // Port Vite (doit correspondre à vite.config.mjs)
            $vite_port = 5174;
            
            wp_enqueue_script(
                'nl-vite-client',
                get_site_url().':'.$vite_port.'/@vite/client',
                [],
                null,
                true
            );

            wp_enqueue_script(
                'nl-main',
                get_site_url().':'.$vite_port.'/assets/js/main.js',
                [],
                null,
                true
            );

            // Add ajaxurl to window for Vite
            add_action( 'wp_footer', function() {
                ?>
                <script>
                    window.ajaxurl = '<?php echo esc_js( admin_url( 'admin-ajax.php' ) ); ?>';
                </script>
                <?php
            } );

            return;
        }

        // Production: use manifest generated by Vite
        $manifest_path = LUNIVERS_THEME_PATH . '/dist/.vite/manifest.json';

        if ( ! file_exists( $manifest_path ) ) {
            return;
        }

        $manifest = json_decode( file_get_contents( $manifest_path ), true );

        // JS
        if ( isset( $manifest['assets/js/main.js']['file'] ) ) {
            wp_enqueue_script(
                'nl-main',
                LUNIVERS_THEME_URI . '/dist/' . $manifest['assets/js/main.js']['file'],
                [],
                LUNIVERS_THEME_VERSION,
                true
            );
        }

        // CSS (via Vite)
        if ( isset( $manifest['assets/js/main.js']['css'] ) ) {
            foreach ( $manifest['assets/js/main.js']['css'] as $css_file ) {
                wp_enqueue_style(
                    'nl-main',
                    LUNIVERS_THEME_URI . '/dist/' . $css_file,
                    [],
                    LUNIVERS_THEME_VERSION
                );
            }
        }
    }

    public function add_module_attribute( $tag, $handle, $src ) {

        // Scripts qui doivent être des modules (Vite)
        $module_handles = [ 'nl-main', 'nl-vite-client' ];
    
        if ( in_array( $handle, $module_handles, true ) ) {
            return sprintf( '<script type="module" src="%1$s"></script>', esc_url( $src ) );
        }
    
        return $tag;
    }
}